- .drone.yml
- README.md
- files/adjust.sh
- files/cleanup.sh
- files/symlink.sh
- pkg.yaml
Signed-off-by: Andrew Rynhard <andrew@andrewrynhard.com>
> feat: initial implementation

- pkg.yaml
This PR will make use of the new bzip2 image
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>
> chore: update bzip2

- .drone.yml
- pkg.yaml
Signed-off-by: Brad Beam <brad.beam@talos-systems.com>
> chore(go): Update go to 1.12.8

- pkg.yaml
Address some issues
Signed-off-by: Brad Beam <brad.beam@talos-systems.com>
> chore: Upgrade go to 1.12.9

- .drone.yml
- pkg.yaml
Signed-off-by: Brad Beam <brad.beam@talos-systems.com>
> chore: Upgrade go to 1.12.10

- Pkgfile
- base/pkg.yaml
- make/pkg.yaml
- tools/pkg.yaml
> chore: use `Pkgfile` vars to expose base image better

- golang/golang/pkg.yaml
No security fixes with this release.
> feat: upgrade Go the latest release 1.13.3

- .drone.yml
- Makefile
- golang/golang/pkg.yaml
Addresses some issues in net/http, scavenger potential panics, etc.
> chore: upgrade Go to 1.13.6

- bzip2/pkg.yaml
- elfutils/pkg.yaml
- golang/golang/pkg.yaml
See https://github.com/golang/go/issues?q=milestone%3AGo1.14.1+label%3ACherryPickApproved
> feat: upgrade Go to 1.14.1

- golang/golang/pkg.yaml
Most interesting feature is support for `-race` on muslc.
> feat: upgrade Go to 1.14.3

- .drone.yml
- Makefile
- Pkgfile
See also https://github.com/talos-systems/toolchain/pull/11
> feat: support for multi-arch image amd64/arm64

- golang/golang/pkg.yaml
See https://golang.org/doc/devel/release.html#go1.14.minor
> feat: upgrade Go to 1.14.6

- .drone.yml
- golang/golang/pkg.yaml
See https://groups.google.com/d/msgid/golang-announce/CALvTBvdg%3DL0AFR7EiPtGP-%3DSbS-6PzeGNVzw3oPYJc8qhix1ig%40mail.gmail.com
> feat: update Go to 1.14.7 (security fix)

- golang/golang/pkg.yaml
See https://golang.org/doc/go1.15
> feat: upgrade Go to 1.15.1

- ca-certificates/pkg.yaml
> feat: upgrade ca-certificates to 2020-07-22

- .drone.yml
- Makefile
- Pkgfile
Just registry/username changes.
> chore: migrate to ghcr.io

- golang/golang/pkg.yaml
See https://golang.org/doc/devel/release.html#go1.15.minor
> feat: bump Go to 1.15.3

- golang/golang/pkg.yaml
> feat: bump Go to 1.15.5

- python3/pkg.yaml
- tools/pkg.yaml
This adds python3.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
> feat: add python3

- golang/golang/pkg.yaml
See https://golang.org/doc/devel/release.html#go1.15.minor
> feat: bump Go to 1.15.6

- Makefile
- protobuf/pkg.yaml
- protoc-gen-go/pkg.yaml
This upgrades protobuf and protoc-gen-go to the latest stable
versions.
> feat: upgrade proto libraries

- protoc-gen-go-grpc/pkg.yaml
- tools/pkg.yaml
See https://github.com/golang/protobuf/issues/1070
> feat: add protoc-gen-go-grpc

- golang/golang/pkg.yaml
See https://golang.org/doc/devel/release.html#go1.15.minor
> feat: bump Go to 1.15.7

- Makefile
- Pkgfile
Does not update deps.png itself.
> chore: make it easier to update deps.png

- golang/golang/pkg.yaml
See https://github.com/golang/go/issues?q=milestone%3AGo1.16.4+label%3ACherryPickApproved
and https://github.com/golang/go/issues?q=milestone%3AGo1.16.5+label%3ACherryPickApproved
> feat: update Go to 1.16.5

- expat/pkg.yaml
https://github.com/libexpat/libexpat/blob/R_2_4_1/expat/Changes
> chore: update expat

- Pkgfile
See https://github.com/talos-systems/talos/issues/4135
See https://github.com/talos-systems/toolchain/pull/29
> chore: bump toolchain for binutils multiarch

- golang/golang/pkg.yaml
See https://golang.org/doc/go1.17 and
https://github.com/golang/go/issues?q=milestone%3AGo1.17.1+label%3ACherryPickApproved
> feat: update Go to 1.17.1

- Pkgfile
There are no actual changes, just retagged image.
> chore: use tagged toolchain 0.3.0

- pcre/pkg.yaml
> feat: update PCRE version and source host

- Pkgfile
See
* https://github.com/talos-systems/toolchain/pull/30
* https://github.com/talos-systems/toolchain/pull/31
> feat: update toolchain with Linux headers 5.15

- ca-certificates/pkg.yaml
- golang/golang/pkg.yaml
See https://github.com/golang/go/milestone/235?closed=1
> feat: update Go to 1.17.4

- squashfs-tools/pkg.yaml
- tools/pkg.yaml
- zstd/pkg.yaml
This adds zstd binaries and libraries and enables zstd in the
mksquashfs.
> feat: support zstd compression

- Makefile
- Pkgfile
> chore: rename org

- .conform.yaml
> chore: enable conform

- Makefile
- Pkgfile
> chore: update bldr

- golang/golang/pkg.yaml
Bump go to 1.18.2
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
> chore: bump go to 1.18.2

- golang/golang/pkg.yaml
Bump go to 1.17.10
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
> chore: bump go to 1.17.10

- golang/golang/pkg.yaml
> feat: update Go to 1.19

- Pkgfile
- expat/pkg.yaml
- file/pkg.yaml
- findutils/pkg.yaml
- flex/pkg.yaml
- gawk/pkg.yaml
- gettext/pkg.yaml
- git/pkg.yaml
- gmp/pkg.yaml
- golang/golang/pkg.yaml
- gperf/pkg.yaml
- grep/pkg.yaml
- gzip/pkg.yaml
- img/pkg.yaml
- kmod/pkg.yaml
- libffi/pkg.yaml
- libseccomp/pkg.yaml
- libtool/pkg.yaml
- libuv/pkg.yaml
- m4/pkg.yaml
- make/pkg.yaml
- meson/pkg.yaml
- mpc/pkg.yaml
- mpfr/pkg.yaml
- musl-fts/pkg.yaml
- musl-obstack/pkg.yaml
- ncurses/pkg.yaml
- openssl/pkg.yaml
This is part 2 of the [PR](https://github.com/siderolabs/tools/pull/216)
> feat: enable renovate dependency updates (2/n)

- .github/renovate.json
- Pkgfile
- pahole/pkg.yaml
- patch/pkg.yaml
- perl/pkg.yaml
- pkg-config/pkg.yaml
- protobuf/pkg.yaml
- protoc-gen-go-grpc/pkg.yaml
- protoc-gen-go/pkg.yaml
- python3/pkg.yaml
- rhash/pkg.yaml
- sed/pkg.yaml
- squashfs-tools/pkg.yaml
- swig/pkg.yaml
- tar/pkg.yaml
- tcl/pkg.yaml
- texinfo/pkg.yaml
- util-linux/pkg.yaml
- xz/pkg.yaml
- zlib/pkg.yaml
- zstd/pkg.yaml
This is the last commit as part of PR's:
- [1/n](https://github.com/siderolabs/tools/pull/216)
- [2/n](https://github.com/siderolabs/tools/pull/218)
> feat: enable renovate dependency updates (3/3)

- tools/pkg.yaml
> chore: add libbpf to tools

- .github/renovate.json
- Pkgfile
> chore: update renovate config

- golang/golang/pkg.yaml
> chore: bump go to 1.19.2

- Pkgfile
See https://www.openssl.org/news/cl111.txt
> feat: update OpenSSL to 1.1.1r

- Makefile
- Pkgfile
- xz/pkg.yaml
> chore: bump tools

- Pkgfile
- xz/pkg.yaml
See https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU
(cherry picked from commit 202f76f26f6a6ebd82a2690f1c50ec825a8b9aab)
> backport: feat: update Go to 1.19.4

- Pkgfile
| Package | Update | Change |
|---|---|---|
| [PCRE2Project/pcre2](https://togithub.com/PCRE2Project/pcre2) | minor | `10.41` -> `10.42` | 
| git://git.kernel.org/pub/scm/git/git.git | minor | `2.38.1` -> `2.39.0` | 
| [https://git.tukaani.org/xz.git](https://git.tukaani.org/xz) | minor | `v5.2.9` -> `v5.4.0` |
| [https://gitlab.inria.fr/mpc/mpc.git](https://gitlab.inria.fr/mpc/mpc) | patch | `1.3.0` -> `1.3.1` | 
| [libbpf/libbpf](https://togithub.com/libbpf/libbpf) | minor | `v1.0.1` -> `v1.1.0` |
| [protocolbuffers/protobuf](https://togithub.com/protocolbuffers/protobuf) | patch | `3.21.11` -> `3.21.12` |
> feat: update releases

- Pkgfile
Release notes https://go.dev/doc/devel/release#go1.19.5
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
> feat: update Go to 1.19.5

- Pkgfile
- gnutls/pkg.yaml
- libtasn1/pkg.yaml
- libunistring/pkg.yaml
- nettle/pkg.yaml
- tools/pkg.yaml
Add gnutls required for u-boot
> feat: add gnutls

- Pkgfile
- xz/pkg.yaml
Bump Golang to 1.19.6
Ref: https://groups.google.com/g/golang-announce/c/V0aBFqaFs_E/m/CnYKgKwBBQAJ
> chore: bump Go to 1.19.6

- Pkgfile
- pcre/pkg.yaml
- swig/pkg.yaml
- tools/pkg.yaml
This partially reverts commit e6c98fdf54425e6382f226e33bccca6f3875aad3, swig is needed for u-boot.
> fix: partially revert e6c98fdf54425e6382f226e33bccca6f3875aad3a

- .github/renovate.json
- Pkgfile
Skip pre-release versions for util-linux.
> chore: skip rc versions for util-linux

- Pkgfile
See https://go.dev/doc/devel/release#go1.20
> feat: update Go to 1.20.3

- Pkgfile
- abseil/pkg.yaml
> chore: bump deps

- Pkgfile
- sbsign/pkg.yaml
- tools/pkg.yaml
> feat: add sbsign

- sd-boot/patches/26445.patch
- sd-boot/pkg.yaml
- sd-stub/patches/26445.patch
- sd-stub/pkg.yaml
Add assetion patch from upstream.
ref: https://github.com/systemd/systemd/issues/26428
> fix: add sd-stub assertion patch

- ncurses/pkg.yaml
- openssl/pkg.yaml
- perl/pkg.yaml
- python3/pkg.yaml
Also disable openssl docs building.
> chore: use same source epoch everywhere

- .github/renovate.json
- Pkgfile
- glib2/pkg.yaml
- json-glib/pkg.yaml
- libtpms/pkg.yaml
- socat/patches/use-linux-headers.patch
- socat/pkg.yaml
- swtpm/pkg.yaml
- tools/pkg.yaml
> feat: add swtpm

- Pkgfile
See https://go.dev/doc/devel/release#go1.20.5
> feat: update Go to 1.20.5

- Pkgfile
See https://go.dev/doc/devel/release#go1.20.7
> feat: update Go to 1.20.7

- Makefile
- Pkgfile
- golang/golang/pkg.yaml
> feat: update Go to 1.21

- Pkgfile
See https://go.dev/doc/devel/release#go1.21.0
> feat: update Go to 1.21.1

- Pkgfile
- python3/pkg.yaml
| Package | Update | Change |
|---|---|---|
| git://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git | major | `30` -> `31` |
| [curl/curl](https://togithub.com/curl/curl) | minor | `8_3_0` -> `8_4_0` |
| [davea42/libdwarf-code](https://togithub.com/davea42/libdwarf-code) | minor | `0.7.0` -> `0.8.0` |
| git://git.savannah.gnu.org/gettext.git | patch | `0.22.2` -> `0.22.3` |
| [grpc/grpc-go](https://togithub.com/grpc/grpc-go) | patch | `v1.58.2` -> `v1.58.3` |
| [mesonbuild/meson](https://togithub.com/mesonbuild/meson) | patch | `1.2.1` -> `1.2.2` |
| [protocolbuffers/protobuf](https://togithub.com/protocolbuffers/protobuf) | minor | `24.3` -> `24.4` |
> feat: update dependencies

- .github/workflows/ci.yaml
Add a dummy GitHub workflow file.
> chore: add dummy gh workflow

- Makefile
> fix: org name

- .github/workflows/ci.yaml
- .github/workflows/slack-notify.yaml
- .github/workflows/weekly.yaml
- Makefile
- Pkgfile
| Package | | Update | Change |
|---|---|---|---|
| [protocolbuffers/protobuf](https://togithub.com/protocolbuffers/protobuf) | |  major | `24.4` -> `25.1` |
| [Perl/perl5](https://togithub.com/Perl/perl5) |  | patch | `5.38.0` -> `5.38.1` |
| git://git.kernel.org/pub/scm/git/git.git |  | minor | `2.42.0` -> `2.43.0` |
| git://git.openssl.org/openssl.git |  | minor | `3.1.4` -> `3.2.0` |
| git://git.savannah.gnu.org/gawk.git |  | minor | `5.2.2` -> `5.3.0` |
| git://git.savannah.gnu.org/gettext.git |  | patch | `0.22.3` -> `0.22.4` |
| git://sourceware.org/git/elfutils.git |  | minor | `0.189` -> `0.190` |
| [https://gitlab.com/gnutls/gnutls.git](https://gitlab.com/gnutls/gnutls) |  | patch | `3.8.1` -> `3.8.2` |
| [libbpf/libbpf](https://togithub.com/libbpf/libbpf) |  | minor | `v1.2.2` …
> feat: bump dependencies

- Pkgfile
See https://go.dev/doc/devel/release#go1.21.5
> feat: update Go to 1.21.5

- Pkgfile
See https://go.dev/doc/devel/release#go1.21.minor
> feat: update Go to 1.21.6

- Pkgfile
- kmod/pkg.yaml
Looks like new version segfaults when used.
> fix: revert kmod to version 31

- Pkgfile
- kmod/pkg.yaml
This reverts commit 6c1f73d4f51fae028a3aa3c97884b80801826a40.
> fix: use musl 1.2.4 in tools, revert kmod back to 32

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
- Pkgfile
> chore: update xz to 5.6.1

- Pkgfile
Update toolchain to bring in
https://github.com/siderolabs/toolchain/pull/102.
> chore: update toolchain

- Pkgfile
> feat: update go to 1.22.2

- Pkgfile
(cherry picked from commit d2746e5a7a60a22ad957c8bc04831bae8c191af6)
> feat: update Go to 1.22.4

- Pkgfile
Latest 1.21 release (release-1.6).
> feat: update Go to 1.21.12

- Pkgfile
> feat: update Go to 1.22.5

- .github/renovate.json
- Pkgfile
- libsepol/patches/busybox-ln.patch
- libsepol/pkg.yaml
- secilc/patches/disable-manpages.patch
- secilc/pkg.yaml
- tools/pkg.yaml
Tested, works in the toolchain container in docker for successfully building my WIP policy
We might be interested in building CIL in runtime like Android does that, but that would be required if we will need to bundle policy at runtime
> feat: secilc for building SELinux policies

- Pkgfile
> feat: update Go to 1.23.1

- Pkgfile
> feat: update Go to 1.22.8

- Pkgfile
- bash/pkg.yaml
- ncurses/pkg.yaml
Update bash to depend on ncurses.
> feat: update toolchain for gcc 14.2

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
- Pkgfile
See https://go.dev/doc/devel/release#go1.23.minor
> feat: update Go to 1.23.3

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
- Pkgfile
- hack/release.sh
> feat: update Go to 1.22.9

- .github/workflows/ci.yaml
- .github/workflows/slack-notify.yaml
- .github/workflows/weekly.yaml
- Makefile
> chore: rekres

- Pkgfile
See https://go.dev/doc/devel/release#go1.23.minor
> feat: update Go to 1.23.4

- .github/renovate.json
- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
> chore: kresify renovate config

- .github/renovate.json
- Makefile
> chore: rekres to fix reproducibility

- Pkgfile
- protoc-gen-go-grpc/pkg.yaml
- protoc-gen-go/pkg.yaml
Pull in new pkgs, also remove unneeded PATH
> feat: update to Go 1.23.6

- Pkgfile
- policycoreutils/pkg.yaml
- tools/pkg.yaml
Update toolchain to include musl fixes, also update curl and fix sbin merge.
> chore: update dependencies

- .kres.yaml
- Makefile
- cmake/pkg.yaml
- curl/pkg.yaml
- elfutils/pkg.yaml
- git/pkg.yaml
- gnutls/pkg.yaml
- libbpf/pkg.yaml
- meson/pkg.yaml
- pyelftools/pkg.yaml
- python-jinja2/pkg.yaml
- python-markupsafe/pkg.yaml
- python-setuptools/pkg.yaml
- python3/pkg.yaml
- swig/pkg.yaml
- tools-pcre2/pkg.yaml
- tools-squashfs-tools/pkg.yaml
- tools-zlib/pkg.yaml
- tools/pkg.yaml
> chore: move zlib to be an external package

- Pkgfile
- tools-kmod/patches/strndupa.patch
- tools-kmod/pkg.yaml
Revert kmod to 33, not sure sure if it's meson or version bump that broke module loading.
> fix: revert kmod to 33

- .github/renovate.json
- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
- Pkgfile
See https://go.dev/doc/devel/release#go1.23.minor
See https://github.com/siderolabs/talos/issues/10498
> feat: update Go to 1.23.7

- Pkgfile
- tools-util-linux/pkg.yaml
See https://github.com/siderolabs/pkgs/pull/1193
> fix: revert util-linux to 2.40.4

- Pkgfile
> backport: feat: update Go to 1.24.3

- Pkgfile
Via toolchain update.
See https://github.com/siderolabs/toolchain/pull/144
> feat: update Go to 1.24.4

- autoconf/pkg.yaml
- automake/pkg.yaml
- bash/pkg.yaml
- bc/pkg.yaml
- bison/pkg.yaml
- coreutils/pkg.yaml
- diffutils/pkg.yaml
- findutils/pkg.yaml
- gawk/pkg.yaml
- gmp/pkg.yaml
- grep/pkg.yaml
- gzip/pkg.yaml
- libtasn1/pkg.yaml
- libunistring/pkg.yaml
- m4/pkg.yaml
- mpc/pkg.yaml
- mpfr/pkg.yaml
- musl-utils/pkg.yaml
- musl-utils/src/getent.c
- ncurses/pkg.yaml
- nettle/pkg.yaml
- patch/pkg.yaml
- sed/pkg.yaml
- texinfo/pkg.yaml
- tools-cpio/pkg.yaml
- tools-tar/pkg.yaml
See https://www.gnu.org/prep/ftp.html
> chore: use ftpmirror for GNU sources

- autoconf/pkg.yaml
- automake/pkg.yaml
- bash/pkg.yaml
- bc/pkg.yaml
- bison/pkg.yaml
- coreutils/pkg.yaml
- diffutils/pkg.yaml
- findutils/pkg.yaml
- gawk/pkg.yaml
- gmp/pkg.yaml
- grep/pkg.yaml
- gzip/pkg.yaml
- libtasn1/pkg.yaml
- libunistring/pkg.yaml
- m4/pkg.yaml
- mpc/pkg.yaml
- mpfr/pkg.yaml
- musl-utils/pkg.yaml
- musl-utils/src/getent.c
- ncurses/pkg.yaml
- nettle/pkg.yaml
- patch/pkg.yaml
- sed/pkg.yaml
- texinfo/pkg.yaml
- tools-cpio/pkg.yaml
- tools-tar/pkg.yaml
See https://www.gnu.org/prep/ftp.html
(cherry picked from commit 0554e87a6e65bf3a561dc55634912ac4a7de737c)
> backport: chore: use ftpmirror for GNU sources

- Pkgfile
- cmake/pkg.yaml
- gmp/patches/gmp-gcc-15.patch
- gmp/pkg.yaml
- ncurses/pkg.yaml
- tools-cpio/patches/gcc-15.patch
- tools-cpio/pkg.yaml
Via toolchain. Also bump and fix some dependencies
Signed-off-by: Dmitrii Sharshakov <dmitry.sharshakov@siderolabs.com>
> feat: update to GCC 15
