siderolabs/tools

pkg.yaml

The fossies site only publishes the latest stable version. Moved to the
actual bzip2 dev site which hosts older versions, though I went ahead an
updated to latest stable while here.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

fix: update bzip2

---

.drone.yml
pkg.yaml

Signed-off-by: Brad Beam <brad.beam@talos-systems.com>

chore: Upgrade to go 1.12.10 to address CVE-2019-16276

---

pkg.yaml

Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

chore: bump golang version to 1.13.1

---

pkg.yaml

Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

chore: update golang to 1.13.1

---

Pkgfile
ca-certificates/pkg.yaml
golang/golang/pkg.yaml

This release contains two security fixes.
Also bump shebang version of bldr to the release tag.

feat: update Go to 1.13.2

---

Makefile
Pkgfile

See https://github.com/talos-systems/toolchain/pull/8
Also removes insecure entitlement from Makefile (copy-paste bug).

chore: bump toolchain image for toolchain refactor

---

ca-certificates/pkg.yaml

Upstream `ca-certificates` bundle has been updated, causing build failure. Pinning the certificate bundle to a specific version should prevent this in the future and also provide more reproducible builds.

fix: Update ca-certificates and pin the download

---

curl/pkg.yaml
git/pkg.yaml
img/pkg.yaml
libseccomp/pkg.yaml
tools/pkg.yaml

`img` allows to build docker images inside the buildkit context which
will be used in Talos build to build app container images inside
buildkit, making sure buildkit is able to track all the dependencies.

chore: add 'img' tool

---

golang/golang/pkg.yaml

This doesn't build or run on Linux 5.3 (my local environment), as
there's a bug in Linux kernel which leads to Go memory corruption.

chore: update Go to 1.14

---

golang/golang/pkg.yaml

Looks like there're some fixes for potential deadlocks:
https://github.com/golang/go/issues?q=milestone%3AGo1.14.2+label%3ACherryPickApproved

feat: upgrade Go to 1.14.2

---

golang/alpine/pkg.yaml
golang/golang/pkg.yaml

As Go 1.4 didn't support ARM architecture, we can't use that to
bootstrap Go compiler on arm64. So instead use Alpine's Go package as
bootstrap to build our Go compiler.

feat: provide Go bootstrap on arm64

---

.drone.yml

This switches amd64 builders to be persistent (running outside of the
build) so that cache persists across the builds.

chore: use persistent builders for caching

---

gettext/pkg.yaml
squashfs-tools/pkg.yaml
swig/pkg.yaml

Some programs need `autopoint` for `autoreconf` to work correctly.

fix: build "full" gettext

---

golang/golang/pkg.yaml

Security release.
This issue is CVE-2020-24553 and Go issue golang.org/issue/40928.

feat: upgrade Go to 1.14.8

---

.drone.yml

This should allow only one build of `tools` per node.

chore: enforce resources on Drone steps

---

make/pkg.yaml

This might have some bugs fixed related to kernel pipe usage and high
`-j` number.

feat: upgrade Make to 4.3

---

libressl/pkg.yaml

It is used at least to build the kernel in `pkgs/`.

feat: update LibreSSL to 3.2.1

---

golang/golang/pkg.yaml

Many important fixes to http2 package:
https://github.com/golang/go/issues?q=milestone%3AGo1.15.4+label%3ACherryPickApproved

feat: update Go to 1.15.4

---

Pkgfile
gmp/pkg.yaml
mpc/pkg.yaml
mpfr/pkg.yaml
tools/pkg.yaml

These libs are used to build gcc in `toolchain`, but as GCC plugins are
built as part of the kernel build, they are required once again. These
builds mirror versions from the toolchain.
Bump toolchain for gcc plugin support.

feat: add gcc math libs for gcc plugins support

---

Pkgfile
libseccomp/pkg.yaml

feat: bump toolchain for libmusl CVE-2020-28928 fix

---

rhash/pkg.yaml

See https://github.com/rhash/RHash/releases/tag/v1.4.1

feat: bump rhash to 1.4.1

---

golang/golang/pkg.yaml

Changes: https://github.com/golang/go/issues?q=milestone%3AGo1.15.8+label%3ACherryPickApproved

feat: update Go to version 1.15.8

---

python3/pkg.yaml

New release of `u-boot` relies on `pkg_resources` module (part of
`setuptools`), so bootstrap Python with pip to include `pkg_resources`
as well.

feat: upgrade Python 3.9.2, enable pip

---

Pkgfile

No-op, just tag updates (same toolchain contents).

chore: bump tools to 0.2.0

---

golang/golang/pkg.yaml

This introduces major 1.16 release plus security fix from 1.16.1.

feat: bump Go to 1.16.1

---

golang/golang/pkg.yaml

See https://groups.google.com/d/msgid/golang-announce/CALvTBvdUGzto375BNFBOsQKGRjqtQx0Y_2W2HZBSTTpXfVS2uA%40mail.gmail.com

feat: bump Go to 1.15.9

---

protobuf/pkg.yaml
protoc-gen-go-grpc/pkg.yaml
protoc-gen-go/pkg.yaml
tools/pkg.yaml

See https://github.com/golang/protobuf/issues/1070
Before this one is merged, Talos build should be updated.
`ghcr.io/aleksi/tools:v0.3.0-23-g00e42a3`

feat: bump protobuf deps, add protoc-gen-go-grpc

---

golang/golang/pkg.yaml

go1.16.2 (released 2021/03/11) includes fixes to cgo, the compiler, linker, the go command, and the syscall and time packages.
See the Go 1.16.2 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.16.2+label%3ACherryPickApproved

chore: bump Go to 1.16.2

---

protobuf/pkg.yaml
protoc-gen-go/pkg.yaml

protoc: 3.15.6
protoc-gen-go: 1.26.0
See also talos-systems/talos#3342

feat: bump protobuf-related tools

---

golang/golang/pkg.yaml

See https://github.com/golang/go/issues?q=milestone%3AGo1.16.3+label%3ACherryPickApproved

feat: update Go to 1.16.3

---

musl-fts/pkg.yaml
musl-obstack/pkg.yaml

Switch musl-fts repo back to upstream.
Update musl-obstack to 1.2.2:
* https://github.com/void-linux/musl-obstack/releases/tag/v1.2
* https://github.com/void-linux/musl-obstack/releases/tag/v1.2.1
* https://github.com/void-linux/musl-obstack/releases/tag/v1.2.2

chore: update musl

---

golang/golang/pkg.yaml

See https://groups.google.com/g/golang-announce/c/n9FxMelZGAQ/m/4ZhvTx0dAQAJ
These minor releases include a security fix according to the new security policy.
> crypto/tls clients can panic when provided a certificate of the wrong type for the negotiated parameters.
> net/http clients performing HTTPS requests are also affected. The panic can be triggered by an attacker
> in a privileged network position without access to the server certificate's private key, as long as a trusted
> ECDSA or Ed25519 certificate for the server exists (or can be issued), or the client is configured with
> Config.InsecureSkipVerify. Clients that disable all TLS_RSA cipher suites (that is, TLS 1.0–1.2 cipher
> suites without ECDHE), as well as TLS 1.3-only clients, are unaffected.
Signed-off-by: Andrey Smirnov …

feat: update Go to 1.16.6

---

golang/golang/pkg.yaml
protoc-gen-go-grpc/pkg.yaml
protoc-gen-go/pkg.yaml

Fixed in Go 1.16.7: https://github.com/golang/go/issues?q=milestone%3AGo1.16.7+label%3ACherryPickApproved
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>

feat: update Go and protoc-gen-go tools

---

cpio/pkg.yaml
perl/pkg.yaml
rhash/pkg.yaml
tar/pkg.yaml

Add dependency on `patch` where it was missing. ~Not really know how it builds
right now without this though.~
This is required as new alpine base image (which is with new bldr version), doesn't have `patch` in the base image.

chore: add patch dependency

---

Pkgfile

This pulls in optimized flow and also bumps alpine to 3.14.

chore: update bldr with new version

---

ncurses/patches/reproducibility.patch
ncurses/pkg.yaml

It was actually used in pkgs, so it should be brought back.
Add a patch to make `.a` libraries reproducible.

fix: restore static library for ncurses

---

golang/golang/pkg.yaml

https://github.com/golang/go/issues?q=milestone%3AGo1.17.3+label%3ACherryPickApproved
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>

feat: update Go to 1.17.3

---

protobuf/pkg.yaml
protoc-gen-go-grpc/pkg.yaml

https://github.com/protocolbuffers/protobuf/blob/3a4d9316aa9e3f0afec58e83ed744b0be4d337fa/CHANGES.txt#L1-L175
https://github.com/grpc/grpc-go/releases/tag/v1.42.0
https://github.com/grpc/grpc-go/releases/tag/v1.41.0
https://github.com/grpc/grpc-go/releases/tag/v1.40.0
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>

feat: update protobuf to 3.19.1, grpc-go to 1.42.0

---

Pkgfile

In preparation for cutting release of tools.

chore: bump toolchain to the final 0.4.0 version

---

golang/golang/pkg.yaml

See https://github.com/golang/go/issues?q=milestone%3AGo1.17.5+label%3ACherryPickApproved

feat: update Go to 1.17.5

---

golang/golang/pkg.yaml

See https://github.com/golang/go/issues?q=milestone%3AGo1.17.5+label%3ACherryPickApproved
(cherry picked from commit 9c2b9dfde84366c486f212cc074405cfb4d52127)

backport: feat: update Go to 1.17.5

---

golang/golang/pkg.yaml

See https://github.com/golang/go/issues?q=milestone%3AGo1.17.6+label%3ACherryPickApproved

feat: update Go to 1.17.6

---

golang/golang/pkg.yaml

Bump go to 1.17.7
Ref: https://groups.google.com/g/golang-announce/c/SUsQn0aSgPQ/m/gx45t8JEAgAJ
Fixes:
- [CVE-2022-23806](https://go.dev/issue/50974)
- [CVE-2022-23772](https://go.dev/issue/50699)
- [CVE-2022-23773](https://go.dev/issue/35671)

chore: bump go to 1.17.7

---

golang/golang/pkg.yaml

Bump go to 1.17.7
Ref: https://groups.google.com/g/golang-announce/c/SUsQn0aSgPQ/m/gx45t8JEAgAJ
Fixes:
- [CVE-2022-23806](https://go.dev/issue/50974)
- [CVE-2022-23772](https://go.dev/issue/50699)
- [CVE-2022-23773](https://go.dev/issue/35671)
(cherry picked from commit 4c9e7a4a01843363e07687b6d2e5145cf8329368)

backport: chore: bump go to 1.17.7

---

expat/pkg.yaml

Bump expat to 2.4.5
Fixes:
- [CVE-2022-25235](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25235)
- [CVE-2022-25236](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25236)
- [CVE-2022-25313](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25313)
- [CVE-2022-25314](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25314)
- [CVE-2022-25315](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25315)
See https://blog.hartwork.org/posts/expat-2-4-5-released/

chore: bump expat to 2.4.5

---

Makefile
Pkgfile
meson/pkg.yaml
openssl/pkg.yaml

* use new bldr version with SOURCE_DATE_EPOCH
* fix reproducibility issues in `meson` and `openssl`
* bump toolchain to the latest reproducible 0.5.0

chore: reproducible builds

---

golang/golang/pkg.yaml

Update Golang to 1.17.8
Fixes: [CVE-2022-24921](https://github.com/golang/go/issues/51112)

chore: update golang to 1.17.8

---

openssl/pkg.yaml

Update OpenSSL to 1.1.1n
Fixes: [CVE-2022-0778](https://lwn.net/Articles/887971/)

chore: update openssl to 1.1.1n

---

zlib/pkg.yaml

Bump zlib to 1.2.12
Fixes: [CVE-2018-25032](https://nvd.nist.gov/vuln/detail/CVE-2018-25032)
Refs:
- https://github.com/advisories/GHSA-jc36-42cf-vqwj
- https://github.com/madler/zlib/issues/605

chore: bump zlib to 1.2.12

---

gzip/pkg.yaml
xz/patches/xzgrep-ZDI-CAN-16587.patch
xz/pkg.yaml

Bump xz to 5.2.5 and gzip to 1.12
Fixes CVE-2022-1271, ZDI-CAN-16587
```text
5.2.5 was released on 2020-03-17. A patch to fix a security vulnerability in xzgrep (CVE-2022-1271, ZDI-CAN-16587) was made public on 2022-04-07. It is a severe issue if an attacker can control the filenames that are given on the xzgrep command line.
```
Ref:
- https://tukaani.org/xz/
- https://www.openwall.com/lists/oss-security/2022/04/07/8

chore: bump xz and gzip

---

golang/golang/pkg.yaml
zlib/pkg.yaml

Bump go to 1.18.1
Fixes:
- [CVE-2022-24675](https://github.com/golang/go/issues/51853)
- [CVE-2022-28327](https://github.com/golang/go/issues/52075)
- [CVE-2022-27536](https://github.com/golang/go/issues/51759)
Also update zlib download url's

chore: bump go to 1.18.1

---

golang/golang/pkg.yaml
zlib/pkg.yaml

Bump go to 1.17.9
Fixes:
- [CVE-2022-24675](https://github.com/golang/go/issues/51853)
- [CVE-2022-28327](https://github.com/golang/go/issues/52075)
- [CVE-2022-27536](https://github.com/golang/go/issues/51759)
Also update zlib download url's to use proper ones

chore: bump go to 1.17.9

---

git/pkg.yaml

Bump git to 2.35.2
Fixes CVE-2022-24765
- https://www.openwall.com/lists/oss-security/2022/04/12/7
- https://github.blog/2022-04-12-git-security-vulnerability-announced/

chore: bump git to 2.35.2

---

coreutils/pkg.yaml

Bump coreutils to 9.1
Ref: https://lwn.net/Articles/891574/

chore: bump coreutils to 9.1

---

git/pkg.yaml

chore: bump git to 2.36.0

---

curl/pkg.yaml

Bump curl to 7.83.0
Fixes:
- https://curl.se/docs/CVE-2022-22576.html
- https://curl.se/docs/CVE-2022-27774.html
- https://curl.se/docs/CVE-2022-27775.html
- https://curl.se/docs/CVE-2022-27776.html

chore: bump curl to 7.83.0

---

util-linux/pkg.yaml

chore: bump util-linux to 2.38

---

ca-certificates/pkg.yaml

Bump ca-certificates to 2022-04-26

chore: bump ca-certificates to 2022-04-26

---

curl/pkg.yaml

Bump curl to 7.83.1
Fixes:
- [CVE-2022-30115](https://curl.se/docs/CVE-2022-30115.html)
- [CVE-2022-27782](https://curl.se/docs/CVE-2022-27782.html)
- [CVE-2022-27781](https://curl.se/docs/CVE-2022-27781.html)
- [CVE-2022-27779](https://curl.se/docs/CVE-2022-27779.html)
- [CVE-2022-27778](https://curl.se/docs/CVE-2022-27778.html)
Ref: https://curl.se/docs/vuln-7.83.0.html

chore: bump curl to 7.83.1

---

Pkgfile

In preparation for Talos 1.1.0-beta.

chore: bump toolchain to v0.6.0

---

golang/golang/pkg.yaml

Fixes:
- [CVE-2022-30634](https://go.dev/issue/52561)
- [CVE-2022-30629](https://go.dev/issue/52814)
- [CVE-2022-30580](https://go.dev/issue/52574)
- [CVE-2022-29804](https://go.dev/issue/52476)

chore: bump golang to 1.18.3

---

golang/golang/pkg.yaml

Fixes:
- [CVE-2022-30634](https://go.dev/issue/52561)
- [CVE-2022-30629](https://go.dev/issue/52814)
- [CVE-2022-30580](https://go.dev/issue/52574)
- [CVE-2022-29804](https://go.dev/issue/52476)

chore: bump golang to 1.17.11

---

openssl/pkg.yaml

Bump OpenSSL to 1.1.1p
Fixes:
- [CVE-2022-1292](https://www.openssl.org/news/vulnerabilities.html#CVE-2022-1292)
- [CVE-2022-2068](https://www.openssl.org/news/vulnerabilities.html#CVE-2022-2068)

chore: bump openssl to 1.1.1p

---

curl/pkg.yaml

Bump curl to 7.84.0
Fixes:
- [CVE-2022-32205](https://curl.se/docs/CVE-2022-32205.html)
- [CVE-2022-32206](https://curl.se/docs/CVE-2022-32206.html)
- [CVE-2022-32207](https://curl.se/docs/CVE-2022-32207.html)
- [CVE-2022-32208](https://curl.se/docs/CVE-2022-32208.html)

chore: bump curl to 7.84.0

---

openssl/pkg.yaml

Bump openssl to [1.1.1q](https://www.openssl.org/news/secadv/20220705.txt)

chore: bump openssl to 1.1.1q

---

golang/golang/pkg.yaml

go1.18.4 (released 2022-07-12) includes security fixes to the
compress/gzip, encoding/gob, encoding/xml, go/parser, io/fs, net/http,
and path/filepath packages, as well as bug fixes to the compiler, the go
command, the linker, the runtime, and the runtime/metrics package.

feat: update Go 1.18.4

---

golang/golang/pkg.yaml

go1.18.4 (released 2022-07-12) includes security fixes to the
compress/gzip, encoding/gob, encoding/xml, go/parser, io/fs, net/http,
and path/filepath packages, as well as bug fixes to the compiler, the go
command, the linker, the runtime, and the runtime/metrics package.
(cherry picked from commit 0d669dd415a044e5279f36c468834848ed6447bf)

backport: feat: update Go 1.18.4

---

argp-standalone/pkg.yaml
dwarfutils/pkg.yaml
elfutils/patches/libdw-dwarf-frame-register.patch
elfutils/pkg.yaml
pahole/patches/libff-to-latest.patch
pahole/pkg.yaml
tools/pkg.yaml

`pahole` is required so the kernel can be built with BTF support.
This commit builds upon the changes from
https://github.com/charlie-haley/tools/tree/feat/add-pahole
Additional changes done:
* Add missing -fPIC flag to argp-standalone
* Add missing dependencies to pahole
* Set TOOLCHAIN prefix for pahole
Signed-off-by: Robert Wunderer <robert.wunderer@caprisys.at>
Address review comments by @smira:
- Add source links to patches needed by pahole
- Refactor build of libdwarf to not rely on bldr internals.
Original PR #210, re-opened the PR get commit GPG signed.
Signed-off-by: Robert Wunderer <robert.wunderer@caprisys.at>

feat: add pahole so kernel can be built with BTF support

---

Pkgfile

Bump toolchain to use [gcc 12](https://github.com/siderolabs/toolchain/pull/36)

chore: bump toolchain

---

Pkgfile

Bump gcc to [12.2.0](https://github.com/siderolabs/toolchain/pull/37)

chore: bump gcc to 12.2.0

---

.github/renovate.json
Pkgfile

Use same renovate config for `Pkgfile` parsing.
Use custom versioning for tcltk/tcl

chore: update renovate config

---

golang/golang/pkg.yaml

chore: bump go to 1.19.1

---

Pkgfile

Bump grpc-go to [v1.49.0](#225)

chore: bump grpc-go

---

Pkgfile

Rever gawk to last stable release, since kernel builds are broken with 5.2.0 gawk.
Ref: https://lists.gnu.org/archive/html/bug-gawk/2022-09/msg00025.html

fix: revert gawk to 5.1.1

---

.drone.yml
Pkgfile

Disable running pipeline for renovate/dependabot pull requests.

chore: disable drone for renovate/dependabot

---

Pkgfile

Updates:
* git 2.38.1
* protoc-gen-go-grpc 1.50.1
* zlib 1.2.13
* protobuf 3.21.8
* python 3.10.8
Reverts:
* openssl 1.1.1q (see https://mta.openssl.org/pipermail/openssl-announce/2022-October/000237.html)
Signed-off-by: Tim Jones <tim.jones@siderolabs.com>

chore: update dependencies

---

Pkgfile
pcre/pkg.yaml
python3/pkg.yaml

Bump Go to 1.19.3
Bump OpenSSL to 1.1.1s
Bump make to 4.4
Bump libffi to 3.4.4
Bump protobuf-cpp to 3.21.9
Bump python to 3.11.0
Bump swig to 4.1.0

chore: bump tools

---

Pkgfile
xz/pkg.yaml

* cmake: 3.25.0
* meson: 0.64.0
* mpfr: 4.1.1
* protoc-gen-go-grpc: 1.51.0
* sed: 4.9
* texinfo: 7.0
* xz: 5.2.8 (switched download URL)

chore: bump dependencies

---

Pkgfile

This PR bumps toolchain to v0.7.0-3-g45b5b5d and mpc to 1.3.0. Renovate bot is also showing updates for golang, but it's an RC and not an actual release.
Finally, it's showing an update to protobuf, but their release process seems to not have published tar.gz files this time. I've added a thread to their forum to ask for clarity about this:
https://groups.google.com/g/protobuf/c/I4EXb4PhYyc
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>

chore: bump toolchain and mpc versions

---

Pkgfile

This PR bumps protobuf to 3.21.11
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>

chore: bump protobuf

---

golang/golang/pkg.yaml

backport: feat: update Go to 1.19.4

---

Makefile

Seems even with bldr update the image is not pushed. Keep provenance disabled.

fix: revert enabling provenance

---

.github/renovate.json
Pkgfile

This should reduce renovate noise.
Also bump texinfo.

chore: reduce renovate noise

---

Pkgfile
golang/bootstrap/pkg.yaml

Go 1.20 requires Go 1.17.13 for bootstrapping, so the built process is as follows:
Go 1.4 -> Go 1.17.13 -> Go 1.20
Ref: https://go.dev/doc/go1.20#bootstrap

feat: update Go to 1.20

---

Pkgfile

This PR bumps toolchain to v0.7.0-10-g1277e2e and protoc-gen-go-grpc to v1.52.3
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>

chore: bump toolchain, bump protoc-gen-go-grpc

---

Pkgfile

Bump Golang to 1.20.1
Ref: https://groups.google.com/g/golang-announce/c/V0aBFqaFs_E/m/CnYKgKwBBQAJ

chore: bump go to 1.20.1

---

.github/renovate.json
Pkgfile
ca-certificates/pkg.yaml
curl/pkg.yaml
expat/pkg.yaml
xz/pkg.yaml

There were error messages about updating curl and libexpat in the renovate app which was missed. Also updates these tools to be latest.

fix: renovate config

---

.github/renovate.json
Pkgfile
abseil/pkg.yaml
protobuf/pkg.yaml
tools/pkg.yaml

protobuf now requires abseil as a dependency.
Ref: https://github.com/protocolbuffers/protobuf/issues/12016

chore: bump deps

---

Pkgfile

See https://github.com/golang/go/issues?q=milestone%3AGo1.19.7+label%3ACherryPickApproved

feat: update Go to 1.19.7

---

protobuf/pkg.yaml

Wrong prefix was used, so `protoc` was missing from final `tools` image.

fix: protoc install

---

Pkgfile

Bump deps:
- toolchain (Kernel to 6.1.19).
- cmake to 3.26.0
- git to 2.40.0
- protobuf to 22.2
- protobuf-go to 1.29.1
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>

chore: bump dep

---

Pkgfile

See https://go.dev/doc/devel/release#go1.20
(cherry picked from commit 1563556b8f8fdf20d8aa58ac5340104c7ffe732e)

backport: feat: update Go to 1.20.3

---

Pkgfile

Bump Golang to 1.20.4.
(cherry picked from commit 47b0fd3e364d4fbcfffe10965f740db7acd82f70)

chore: bump go to 1.20.4

---

.github/renovate.json
Pkgfile
gnuefi/patches/no-werror.patch
gnuefi/pkg.yaml
libcap2/pkg.yaml
tools/pkg.yaml

Add libcap and gnu-efi. This is required for building `sd-stub` and `sd-boot`.

feat: add libcap and gnuefi

---

gnutls/pkg.yaml
golang/golang/pkg.yaml
tools/pkg.yaml

Drop stuff we don't need in the final image.
Before:
```
4.0K	./var
32K	./doc
252K	./etc
2.2M	./sbin
3.6M	./man
4.2M	./x86_64-linux-musl
36M	./include
98M	./libexec
138M	./share
163M	./bin
262M	./lib
263M	./go
969M	.
```
After:
```
4.0K	./var
32K	./doc
252K	./etc
2.2M	./sbin
3.6M	./man
4.2M	./x86_64-linux-musl
36M	./include
61M	./share
98M	./libexec
163M	./bin
239M	./go
262M	./lib
867M	.
```
So -100M (uncompressed).

chore: optimize tools image size

---

Pkgfile

```
OpenSSL 1.1.1v is now available, including bug and security fixes
```

feat: update OpenSSL to 1.1.1v

---

Pkgfile

See https://go.dev/doc/devel/release#go1.20.7
(cherry picked from commit 640e523c1cebfe613f81f10d06b80f1c4912e06e)

backport: feat: update Go to 1.20.7

---

Pkgfile
openssl/pkg.yaml

OpenSSL 1.1.x is reaching EoL, so time to jump.

feat: update OpenSSL to 3.1.3

---

.github/workflows/ci.yaml
.github/workflows/cron.yaml

Refactor GitHub actions to use the manually retrieved labels as triggers instead on triggering on labels.

chore: refactor github actions

---

Pkgfile

See https://github.com/golang/go/issues?q=milestone%3AGo1.21.4+label%3ACherryPickApproved

feat: update Go to 1.21.4

---

Pkgfile

See https://go.dev/doc/devel/release#go1.21.5
(cherry picked from commit 1659d82e78511522e2820efccb892235d6d7b279)

backport: feat: update Go to 1.21.5

---

Pkgfile

See https://go.dev/doc/devel/release#go1.21.minor
(cherry picked from commit a80a2aa0307d90f07c8a239459191a3f68cdd5d3)

backport: feat: update Go to 1.21.6

---

Pkgfile

This is the latest Go 1.20.x (for Talos 1.5.x).

feat: update Go to 1.20.13

---

Pkgfile

crypto/x509: Verify panics on certificates with an unknown public key algorithm
Verifying a certificate chain which contains a certificate with an unknown public key algorithm will cause Certificate.Verify to panic.
This affects all crypto/tls clients, and servers that set Config.ClientAuth to VerifyClientCertIfGiven or RequireAndVerifyClientCert. The default behavior is for TLS servers to not verify client certificates.
Thanks to John Howard (Google) for reporting this issue.
This is CVE-2024-24783 and Go issue https://go.dev/issue/65390.
net/http: memory exhaustion in Request.ParseMultipartForm
When parsing a multipart form (either explicitly with Request.ParseMultipartForm or implicitly with Request.FormValue, Request.PostFormValue, or Request.FormFile), limits on the total size of the …

feat: update Go to 1.22.1

---

Pkgfile

crypto/x509: Verify panics on certificates with an unknown public key algorithm
Verifying a certificate chain which contains a certificate with an unknown public
key algorithm will cause Certificate.Verify to panic.
This affects all crypto/tls clients, and servers that set Config.ClientAuth to
VerifyClientCertIfGiven or RequireAndVerifyClientCert. The default behavior is
for TLS servers to not verify client certificates.
Thanks to John Howard (Google) for reporting this issue.
This is CVE-2024-24783 and Go issue https://go.dev/issue/65390.
net/http: memory exhaustion in Request.ParseMultipartForm
When parsing a multipart form (either explicitly with Request.ParseMultipartForm or implicitly with Request.FormValue, Request.PostFormValue, or Request.FormFile), limits on the total size of the …

feat: update Go to 1.21.8 

---

Pkgfile
sd-boot/pkg.yaml

Bump systemd to `255` and fix renovate matcher for systemd.

chore: bump systemd

---

Pkgfile
xz/pkg.yaml

This downgrades xz version to `v5.4.5` which is the same version other distros have downgraded to.
Sidero repos are not affected, just downgrading as a safe precaution.
Ref: https://www.openwall.com/lists/oss-security/2024/03/29/4
Also pulls in the latest stable toolchain.

fix: xz vulnerability

---

Pkgfile

(cherry picked from commit bd405ff5d8d511eeef17f0a6126ad6cdd3a849bb)

backport: feat: update go to 1.22.2

---

Pkgfile

(cherry picked from commit https://github.com/smira/tools/commit/c34ec5bfd44faa4a5ccced07136246fb25858635)

backport: feat: update go to 1.22.3

---

Pkgfile

[core-8-6-14.tar.gz](https://github.com/user-attachments/files/16708413/core-8-6-14.tar.gz)
[tcl-orig.tar.gz](https://github.com/user-attachments/files/16708414/tcl-orig.tar.gz)
Apparently Github tag was re-tagged
diffoscope ./tcl-orig.tar.gz ./core-8-6-14.tar.gz
--- ./tcl-orig.tar.gz
+++ ./core-8-6-14.tar.gz
│   --- tcl-orig.tar
├── +++ core-8-6-14.tar
│┄ Format-specific differences are supported for tape archives (.tar) but no file-specific differences were detected; falling back to a binary diff. file(1) reports: POSIX tar archive
│ @@ -26,18 +26,18 @@
│  00000190: 0000 0000 0000 0000 0000 0000 0000 0000  ................
│  000001a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
│  000001b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
│  000001c0: 0000 0000 …

fix: fix Tcl tag hashes

---

Pkgfile
fakeroot/patches/fakeroot-no64.patch
fakeroot/patches/fix-shell.patch
fakeroot/patches/no-docs.patch
fakeroot/pkg.yaml
tools/pkg.yaml

fakeroot helps us set SELinux labels which do not exist on host or work on non-SELinux hosts.

feat: add fakeroot as a build dependency

---

Pkgfile

Latest 1.22.x release.
These minor releases include 3 security fixes following the security policy:
go/parser: stack exhaustion in all Parse* functions
Calling any of the Parse functions on Go source code which contains deeply nested literals can cause a panic due to stack exhaustion.
This is CVE-2024-34155 and Go issue https://go.dev/issue/69138.
encoding/gob: stack exhaustion in Decoder.Decode
Calling Decoder.Decode on a message which contains deeply nested structures can cause a panic due to stack exhaustion.
This is a follow-up to CVE-2022-30635.
Thanks to Md Sakib Anwar of The Ohio State University (anwar.40@osu.edu) for reporting this issue.
This is CVE-2024-34156 and Go issue https://go.dev/issue/69139.
go/build/constraint: stack exhaustion in Parse
Calling Parse on a "// +build" …

feat: update Go to 1.22.7

---

Pkgfile
gettext/pkg.yaml

The `master` branch has fixes for `autoconf` which are required in `pkgs` (e.g. `grub` build fails with the release, but passes with `master`).

fix: bump gettext-tiny to the latest dev version

---

Pkgfile

See https://go.dev/doc/devel/release#go1.23.minor

feat: update Go to 1.23.2

---

.github/workflows/ci.yaml
.github/workflows/weekly.yaml
Pkgfile
hack/release.sh

| Package | Update | Change |
|---|---|---|
| [protocolbuffers/protobuf](https://redirect.github.com/protocolbuffers/protobuf) | major | `27.4` -> `28.2` |
| [curl/curl](https://redirect.github.com/curl/curl) | minor | `8_9_1` -> `8_10_1` |
| git://git.kernel.org/pub/scm/git/git.git | minor | `2.46.0` -> `2.47.0` |
| git://git.kernel.org/pub/scm/utils/dtc/dtc.git | patch | `1.7.0` -> `1.7.1` |
| git://git.savannah.gnu.org/gawk.git | patch | `5.3.0` -> `5.3.1` |
| git://git.savannah.gnu.org/texinfo.git | patch | `7.1` -> `7.1.1` |
| [grpc/grpc-go](https://redirect.github.com/grpc/grpc-go) | minor | `v1.65.0` -> `v1.67.1` |
| https://github.com/sabotage-linux/gettext-tiny.git | digest | `070f01d` -> `55a8ae9` |
| [libbpf/libbpf](https://redirect.github.com/libbpf/libbpf) | patch | `v1.4.5` …

feat: bump dependencies

---

Pkgfile

Fixes `fakeroot` being crazy slow.

fix: update for musl with close_range

---

Pkgfile

Last bump before cutting release-1.10.
| Package | Update | Change |
|---|---|---|
| [file/file](https://redirect.github.com/file/file) | minor | `5_45` -> `5_46` |
| [protocolbuffers/protobuf](https://redirect.github.com/protocolbuffers/protobuf) | major | `28.3` -> `29.0` |

feat: bump deps

---

pahole/pkg.yaml
protobuf/pkg.yaml

Avoid breaking multilib symlinks

fix: do not install anything to /usr/lib64

---

Pkgfile

Latest point release for Go 1.22 series, with some bug and security fixes.

feat: update Go to 1.22.12

---

policycoreutils/pkg.yaml

fix: install policycoreutils under correct prefix

---

Pkgfile

We no longer build any systemd targets in tools.

chore: remove systemd version

---

Pkgfile

New API is not compatible with some SBC support packages.
Fixes: https://github.com/siderolabs/sbc-rockchip/pull/58
Signed-off-by: Dmitrii Sharshakov <dmitry.sharshakov@siderolabs.com>

fix: revert swig update

---

Pkgfile

The latest Go release for Talos 1.9.6.
See https://github.com/siderolabs/talos/issues/10811

feat: update Go to 1.23.8

---

Pkgfile

This allows to add a parallel Go 1.23 tooclhain.

chore: update toolchain to the latest version

---

Pkgfile

Preparing to cut tools 1.11.0, no changes to toolchain (just a tagged release).

feat: update toolchain to 1.11.0

---

.github/workflows/ci.yaml
.github/workflows/slack-notify-ci-failure.yaml
.github/workflows/slack-notify.yaml
.github/workflows/stale.yml
.github/workflows/weekly.yaml
Makefile
Pkgfile

Run rekres, update openssl, curl, libexpat and
update all checksums.
| Package | Type | Update | Change |
|---|---|---|---|
| [curl/curl](https://redirect.github.com/curl/curl) |  | minor | `8_15_0` -> `8_16_0` |
| [libexpat/libexpat](https://redirect.github.com/libexpat/libexpat) |  | patch | `2_7_1` -> `2_7_2` |
| [openssl/openssl](https://redirect.github.com/openssl/openssl) |  | patch | `3.5.2` -> `3.5.3` |
| | rekres | | |
| [actions/stale](https://redirect.github.com/actions/stale) | action | major | `v9.1.0` -> `v10.0.0` |
| [siderolabs/bldr](https://redirect.github.com/siderolabs/bldr) |  | patch | `v0.5.3` -> `v0.5.4` |
Signed-off-by: Mateusz Urbanek <mateusz.urbanek@siderolabs.com>

chore: update openssl, curl, libexpat and rekres
